-- =====================================================
-- Migración 015: Baseline retroactivo del esquema "obras"
-- =====================================================
-- ATENCIÓN: Esta migración es DOCUMENTAL, no se aplica.
-- Las tablas ya existen en Supabase desde antes del control de versiones.
-- Este archivo registra el estado real tal como existe hoy (2026-07-26).
--
-- Contexto:
-- Durante la Fase 0 se descubrió que 6 tablas del modelo "obras" existen
-- en producción con datos reales (72 sensores, 145 mediciones) pero sin
-- archivo de migración correspondiente. Fueron creadas por otra vía
-- (probablemente Codex trabajando directo contra Supabase).
--
-- Decisión (ADR 001, 2026-07-26):
-- Este esquema se adopta como modelo de dominio de faenas para Fases 1-3.
-- La migración 014 (monitoring_rounds) no se aplica para este propósito.
--
-- Datos actuales (verificados con COUNT(*), 2026-07-26):
-- - obras: 6 filas
-- - campanas: 7 filas
-- - jornadas: 0 filas
-- - sensores: 72 filas
-- - mediciones: 145 filas
-- - estacionamientos: 22 filas
--
-- Referencias:
-- - MEMORIA.md §3, §10
-- - FASE_0_INVENTARIO_COMPLETO.md
-- - docs/adr/001-adopt-obras-schema-as-work-domain-model.md
-- =====================================================

-- =====================================================
-- 1. TABLA: obras
-- Proyectos de obra (equivalente a "projects" pero en español)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.obras (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre TEXT NOT NULL,
  ubicacion TEXT,
  tipo TEXT,
  estado TEXT NOT NULL DEFAULT 'activa',
  fecha_inicio DATE,
  notas TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.obras ENABLE ROW LEVEL SECURITY;

CREATE POLICY "obras read"
  ON public.obras
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "obras admin insert"
  ON public.obras
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "obras admin update"
  ON public.obras
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "obras admin delete"
  ON public.obras
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.obras IS 'Proyectos de obra. Convive con "projects" (ADR 001): projects para stations/prisms, obras para campanas/faenas.';
COMMENT ON COLUMN public.obras.estado IS 'Estado de la obra: activa, pausada, cerrada';
COMMENT ON COLUMN public.obras.tipo IS 'Tipo de obra: metro, edificación, túnel, etc.';

-- =====================================================
-- 2. TABLA: campanas
-- Campañas de medición (ciclos de observación por obra)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.campanas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  obra_id BIGINT NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  nombre TEXT,
  fecha DATE NOT NULL,
  archivo_txt TEXT,
  estado TEXT NOT NULL DEFAULT 'importada',

  -- Resumen estadístico de la campaña
  total_sensores INTEGER NOT NULL DEFAULT 0,
  medidos INTEGER NOT NULL DEFAULT 0,
  no_medidos INTEGER NOT NULL DEFAULT 0,
  nuevos INTEGER NOT NULL DEFAULT 0,
  cobertura_pct DOUBLE PRECISION,

  -- Evaluación de movimientos
  mov_ok INTEGER NOT NULL DEFAULT 0,
  mov_prealerta INTEGER NOT NULL DEFAULT 0,
  mov_alerta INTEGER NOT NULL DEFAULT 0,
  coord_incoherentes INTEGER NOT NULL DEFAULT 0,
  max_asiento_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
  max_levante_mm DOUBLE PRECISION NOT NULL DEFAULT 0,

  -- Metadata de importación
  fichero_origen TEXT,
  operador TEXT,
  descripcion TEXT,
  estacionamiento TEXT, -- Referencia textual al estacionamiento usado

  -- Relación opcional con jornada de trabajo
  jornada_id BIGINT REFERENCES public.jornadas(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_campanas_obra_id ON public.campanas(obra_id);
CREATE INDEX idx_campanas_fecha ON public.campanas(fecha DESC);
CREATE INDEX idx_campanas_jornada_id ON public.campanas(jornada_id) WHERE jornada_id IS NOT NULL;

ALTER TABLE public.campanas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "campanas read"
  ON public.campanas
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "campanas operativo insert"
  ON public.campanas
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_operativo());

CREATE POLICY "campanas operativo update"
  ON public.campanas
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_operativo())
  WITH CHECK (is_operativo());

CREATE POLICY "campanas admin delete"
  ON public.campanas
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.campanas IS 'Ciclos de medición por obra. Contiene resumen estadístico (cobertura, movimientos) calculado post-importación.';
COMMENT ON COLUMN public.campanas.estado IS 'Estado de la campaña: importada, validada, cerrada';
COMMENT ON COLUMN public.campanas.cobertura_pct IS 'Porcentaje de sensores medidos sobre total esperado';
COMMENT ON COLUMN public.campanas.mov_ok IS 'Cantidad de sensores con movimiento dentro de límites normales';
COMMENT ON COLUMN public.campanas.mov_prealerta IS 'Cantidad de sensores en rango de prealerta';
COMMENT ON COLUMN public.campanas.mov_alerta IS 'Cantidad de sensores en rango de alerta';

-- =====================================================
-- 3. TABLA: jornadas
-- Jornadas de trabajo (sesiones de topógrafo en campo)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.jornadas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  obra_id BIGINT NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  topografo TEXT,
  fecha DATE NOT NULL,
  notas TEXT,
  estado TEXT NOT NULL DEFAULT 'abierta',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_jornadas_obra_id ON public.jornadas(obra_id);
CREATE INDEX idx_jornadas_fecha ON public.jornadas(fecha DESC);

ALTER TABLE public.jornadas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "jornadas read"
  ON public.jornadas
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "jornadas operativo insert"
  ON public.jornadas
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_operativo());

CREATE POLICY "jornadas operativo update"
  ON public.jornadas
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_operativo())
  WITH CHECK (is_operativo());

CREATE POLICY "jornadas admin delete"
  ON public.jornadas
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.jornadas IS 'Jornadas de trabajo en campo. Agrupa campañas realizadas en una sesión por un topógrafo.';
COMMENT ON COLUMN public.jornadas.estado IS 'Estado de la jornada: abierta, cerrada';

-- =====================================================
-- 4. TABLA: sensores
-- Catálogo de puntos de control por obra
-- =====================================================

CREATE TABLE IF NOT EXISTS public.sensores (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  obra_id BIGINT NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL,

  -- Coordenadas de referencia
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  cota_ref DOUBLE PRECISION,

  -- Sistema de coordenadas local/proyectado
  east DOUBLE PRECISION,
  north DOUBLE PRECISION,
  z_local DOUBLE PRECISION,
  coords_calculadas BOOLEAN NOT NULL DEFAULT FALSE,

  -- Clasificación
  itinerario TEXT,
  tipo_sensor TEXT DEFAULT 'nivelacion',
  estado TEXT DEFAULT 'activo',

  -- Metadata
  fecha_instalacion DATE,
  notas TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (obra_id, codigo)
);

CREATE INDEX idx_sensores_obra_id ON public.sensores(obra_id);
CREATE INDEX idx_sensores_codigo ON public.sensores(codigo);
CREATE INDEX idx_sensores_tipo ON public.sensores(tipo_sensor);

ALTER TABLE public.sensores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sensores read"
  ON public.sensores
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "sensores admin insert"
  ON public.sensores
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "sensores admin update"
  ON public.sensores
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "sensores admin delete"
  ON public.sensores
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.sensores IS 'Catálogo de puntos de control (sensores, prismas, referencias) por obra. Equivalente a "control_points" de migración 014 (descartada).';
COMMENT ON COLUMN public.sensores.codigo IS 'Código único del sensor dentro de la obra (ej: CN3, PT-01)';
COMMENT ON COLUMN public.sensores.tipo_sensor IS 'Tipo de sensor: nivelacion, prisma, inclinometro, piezometro, etc.';
COMMENT ON COLUMN public.sensores.coords_calculadas IS 'TRUE si east/north/z_local fueron calculadas (no importadas directamente)';

-- =====================================================
-- 5. TABLA: mediciones
-- Observaciones individuales por campaña y sensor
-- =====================================================

CREATE TABLE IF NOT EXISTS public.mediciones (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  obra_id BIGINT NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  campana_id BIGINT NOT NULL REFERENCES public.campanas(id) ON DELETE CASCADE,
  estacionamiento_id BIGINT REFERENCES public.estacionamientos(id) ON DELETE SET NULL,
  sensor_id BIGINT REFERENCES public.sensores(id) ON DELETE SET NULL,

  -- Identificación del punto medido
  point_id_csv TEXT NOT NULL, -- Código del punto tal como viene en el archivo importado
  fecha_medicion TEXT NOT NULL,

  -- Valores observados
  elev_medida DOUBLE PRECISION NOT NULL,
  east_csv DOUBLE PRECISION,
  north_csv DOUBLE PRECISION,

  -- Metadata de medición
  instrumento TEXT,
  comentario TEXT,

  -- Cálculos y validaciones
  desnivel DOUBLE PRECISION,
  movimiento TEXT NOT NULL DEFAULT 'ok', -- ok, prealerta, alerta
  estado_match TEXT NOT NULL, -- exact, fuzzy, new, unmatched
  tipo_punto TEXT NOT NULL DEFAULT 'sensor', -- sensor, referencia, control
  coordenadas_ok BOOLEAN NOT NULL DEFAULT TRUE,
  dist_xy_m DOUBLE PRECISION,
  posible_typo BOOLEAN NOT NULL DEFAULT FALSE,
  similar_a TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mediciones_obra_id ON public.mediciones(obra_id);
CREATE INDEX idx_mediciones_campana_id ON public.mediciones(campana_id);
CREATE INDEX idx_mediciones_sensor_id ON public.mediciones(sensor_id) WHERE sensor_id IS NOT NULL;
CREATE INDEX idx_mediciones_point_id ON public.mediciones(point_id_csv);
CREATE INDEX idx_mediciones_movimiento ON public.mediciones(movimiento) WHERE movimiento != 'ok';

ALTER TABLE public.mediciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mediciones read"
  ON public.mediciones
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "mediciones admin insert"
  ON public.mediciones
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "mediciones admin update"
  ON public.mediciones
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "mediciones admin delete"
  ON public.mediciones
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.mediciones IS 'Observaciones individuales por campaña. Incluye validación integrada (matching, coordenadas, movimiento). Equivalente a "instrument_readings" de migración 014 (descartada) pero con validación propia.';
COMMENT ON COLUMN public.mediciones.estado_match IS 'Resultado del matching point_id_csv vs. sensores.codigo: exact (encontrado tal cual), fuzzy (encontrado con normalización), new (sensor nuevo), unmatched (no encontrado)';
COMMENT ON COLUMN public.mediciones.movimiento IS 'Evaluación de movimiento respecto a campaña anterior: ok (dentro de límites), prealerta, alerta';
COMMENT ON COLUMN public.mediciones.posible_typo IS 'TRUE si el point_id_csv es similar a otro código existente pero no idéntico (ej: CN3 vs CN-3)';

-- =====================================================
-- 6. TABLA: estacionamientos
-- Setups de estación total por campaña
-- =====================================================

CREATE TABLE IF NOT EXISTS public.estacionamientos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  campana_id BIGINT NOT NULL REFERENCES public.campanas(id) ON DELETE CASCADE,
  obra_id BIGINT NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  fichero_origen TEXT,
  formato TEXT,
  operador TEXT,
  total_lecturas INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_estacionamientos_campana_id ON public.estacionamientos(campana_id);
CREATE INDEX idx_estacionamientos_obra_id ON public.estacionamientos(obra_id);

ALTER TABLE public.estacionamientos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "estacionamientos read"
  ON public.estacionamientos
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (is_active_user());

CREATE POLICY "estacionamientos admin insert"
  ON public.estacionamientos
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "estacionamientos admin update"
  ON public.estacionamientos
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "estacionamientos admin delete"
  ON public.estacionamientos
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (is_admin());

COMMENT ON TABLE public.estacionamientos IS 'Setups de estación total por campaña. Versión simplificada de total_station_setups (que tiene estructura más detallada con orientación/backsight).';
COMMENT ON COLUMN public.estacionamientos.formato IS 'Formato del archivo importado: CSV, Leica GSI, Trimble, etc.';

-- =====================================================
-- 7. FUNCIONES RLS (documentación)
-- =====================================================
-- Las políticas RLS referencian tres funciones:
-- - is_active_user(): verifica que el usuario esté autenticado y activo
-- - is_operativo(): verifica rol "operativo" o superior (puede crear/editar campañas)
-- - is_admin(): verifica rol "admin" (puede borrar y modificar obras/sensores)
--
-- Estas funciones existen en Supabase pero no están documentadas en migraciones
-- locales. Pendiente: migración 018_rls_functions_baseline.sql que las capture.
-- =====================================================

-- =====================================================
-- FIN DE MIGRACIÓN 015 (DOCUMENTAL, NO APLICAR)
-- =====================================================
